# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a106934a6bdc4d2d4af480298c0b5a9836c5560916a3b5dbcfb23d64bf4b6a71b329d73f3cae5e07793337df2605bd2e73fac155906abd860baf27e217a51081

test:
  secret_key_base: e823670caea43576af9e0f42669c6dbeb285d867f32c1414b2f5424201657f79ecf77d430cba181f035480980ca2ce5112662db1a339b979a840a4741c760604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a106934a6bdc4d2d4af480298c0b5a9836c5560916a3b5dbcfb23d64bf4b6a71b329d73f3cae5e07793337df2605bd2e73fac155906abd860baf27e217a51081
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
